import assert from 'node:assert/strict';
import { DreamModel } from '../test/scratch/model/dream.js';
const model = new DreamModel();
assert.equal(model.count, 0);
assert.equal(model.add(0).word, 'light');
const custom = model.add(1, 'A calm ocean remembers');
assert.equal(custom.word, 'ocean');
assert.equal(custom.emotion, 'calm');
assert.equal(custom.kind, 'your thought');
assert.equal(model.add(2, 'ocean').repeats, 2);
assert.equal(model.add(3, 'I miss the moon').emotion, 'longing');
assert.equal(model.add(4, '星空と未来').word, '星空と未来');
assert.equal(model.add(5, 'x'.repeat(200)).text.length, 120);
for (let i = 0; i < 3000; i++) model.add(i + 10, i % 3 ? `uniqueconcept${i}` : undefined);
assert.equal(model.count, 3006);
assert.equal(model.events.length, 18);
assert.equal(model.memories.size, 64);
assert.ok(model.events.every(e => e.text && e.word && Number.isFinite(e.seed)));
assert.equal(new Set(model.events.map(e => e.id)).size, 18);
console.log('PASS: 3,006 events; input bounds, Unicode, emotion mapping, repeated concepts, unique IDs, and bounded event/memory retention.');
